using System.Collections.Generic;

namespace Gust.Persist
{
    public class EntityInfo
    {
        protected internal EntityInfo()
        {
        }

        public PersistenceManager ContextProvider { get; internal set; }
        public object Entity { get; internal set; }
        public EntityState EntityState { get; set; }
        public Dictionary<string, object> OriginalValuesMap { get; set; }
        public bool ForceUpdate { get; set; }
        public AutoGeneratedKey AutoGeneratedKey { get; set; }
        public Dictionary<string, object> UnmappedValuesMap { get; set; }
    }
}