namespace Gust.Keys
{
    /// <summary>
    /// The client is telling us that we should assume that a key will be auto generated in the DB.
    /// We use this class to store the temp value we give the property when it is send to the DB with the DB generated
    /// value we get back
    /// TODO: I'm not sure the client needs to be sending this at all. the server knows what can/must be auto genereted. 
    /// and all the client needs to be told later is what old/temporary keys should be mapped to new ones.
    /// </summary>
    public class AutoGeneratedKey
    {
        public string PropertyName { get; set; }
        public AutoGeneratedKeyType AutoGeneratedKeyType;
        public object TempValue;
        public object RealValue;
    }
}