namespace Gust.Keys
{
    public enum AutoGeneratedKeyType
    {
        /// <summary>
        /// The key should be set by the client
        /// </summary>
        None,

        /// <summary>
        /// The DB should create the key
        /// </summary>
        Identity
    }
}