using System;
using System.Reflection;

namespace Gust
{
    /// <summary>
    /// The client is telling us that we should assume that a key will be auto generated in the DB.
    /// We use this class to store the temp value we give the property when it is send to the DB with the DB generated
    /// value we get back
    /// </summary>
    public class AutoGeneratedKey
    {
        public string PropertyName { get; set; }
        public AutoGeneratedKeyType AutoGeneratedKeyType;

        /// NOT SURE ABOUT THIS
        //public PropertyInfo Property { get; set; }

        public Object TempValue;
        public Object RealValue;
        //PropertyInfo _property;
    }
}