using Gust.Keys;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace Gust
{
    /// <summary>
    /// Holds all the information needed to save a single entity.
    /// </summary>
    public class EntityInfo
    {
        /// <summary>
        ///  The default ctor is provided for serealization and testing only
        /// </summary>
        public EntityInfo() { }

        /// <summary>
        /// Use the "CreateEntityInfo" method on the persis manager if you want to create EntityInfo yourself.
        /// The default ctor is provided for serealization and testing only
        /// </summary>
        internal EntityInfo(EntitySetInfo entitySetInfo,  object entity, EntityState entityState, AutoGeneratedKey autoGeneratedKey, Dictionary<string, object> originalValuesMap, Dictionary<string, object> unmappedValuesMap)
        {
            EntitySetInfo = entitySetInfo;
            Type = entitySetInfo.ClrType;
            Entity = entity;
            EntityState = entityState;
            AutoGeneratedKey = autoGeneratedKey;
            OriginalValuesMap = originalValuesMap ?? new Dictionary<string, object>();
            UnmappedValuesMap = unmappedValuesMap ?? new Dictionary<string, object>();
        }

        public EntitySetInfo EntitySetInfo { get; set; }
        public Type Type { get; set; }
        public object Entity { get; internal set; }
        public EntityState EntityState { get; set; }
        public AutoGeneratedKey AutoGeneratedKey { get; set; }
        public Dictionary<string, object> OriginalValuesMap { get; set; }
        public Dictionary<string, object> UnmappedValuesMap { get; set; }
    }
}