using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace Gust
{
    public class EntityInfo
    {
        protected internal EntityInfo()
        {
        }

        public EntitySetInfo EntitySetInfo { get; set; }
        public Type Type { get; set; }
        public object Entity { get; internal set; }
        public EntityState EntityState { get; set; }
        public Dictionary<string, object> OriginalValuesMap { get; set; }
        public AutoGeneratedKey AutoGeneratedKey { get; set; }
        public Dictionary<string, object> UnmappedValuesMap { get; set; }
    }
}