namespace Gust.Persist
{
    public enum AutoGeneratedKeyType
    {
        None,

        Identity,

        /// <summary>
        /// Should avoid using this option and delete it when we know we can.
        /// </summary>
        KeyGenerator
    }
}